test: test
device: cuda
random_seed: 42
trust_remote_code: True
task: multilabel

dataset:
  name: HSN
  width: 1024
  height: 128
  num_classes: 21
  in_channels: 1
  num_workers: 3
  val_split: 0.25
  classlimit: 500
  eventlimit: 1
  sampling_rate: 32000
  pos_weight: 20 # pos_weight arg in the BCE loss

path:
  output_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/output
  data_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/data_birdset/HSN/
  model_dir: ./storage/pretrained_models
  hf_path: DBD-research-group/BirdSet
  pretrained_weights_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/pretraining-checkpoints/EAT-base_epoch30_pt.pt

model:
  learning_rate: 1e-3
  weight_decay: 5e-2
  num_epochs: 100

wandb:
  project: Finetuning-BirdSet
  run_name: finetuning-HSN-Test