test: test
device: cuda
random_seed: 42
trust_remote_code: True
task: multilabel

dataset:
  name: NBP
  width: 1024
  height: 128
  num_classes: 51
  in_channels: 1
  num_workers: 3
  val_split: 0.25
  classlimit: 500
  eventlimit: 1
  sampling_rate: 16000

path:
  output_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/output
  data_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/data_birdset/NBP/
  model_dir: ./storage/pretrained_models
  hf_path: DBD-research-group/BirdSet
  pretrained_weights_dir: /mnt/stud/work/deeplearninglab/ss2024/ssl-1/pretraining-checkpoints/checkpoint_4_400000.pt

model:
  learning_rate: 2e-4
  weight_decay: 2e-5
  num_epochs: 100
  pos_weight: null
  granularity: utterance
  loss: BCE

wandb:
  project: Finetuning-BirdSet
  run_name: NBP-non-linear-16kHz