defaults:
  - _self_
  - model: swin_vit
  - dataset: hsn

device: cuda
random_seed: 42
trust_remote_code: True
task: multilabel

path:
  output_dir: ./output
  data_dir: ./data
  model_dir: ./storage/pretrained_models
  hf_path: DBD-research-group/BirdSet
  pretrained_weights_dir: ./pretrained_weights/vit_swin_save_state_example.pth


hydra:
  run:
    dir: ${path.output_dir}